---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: sigsci-service-deployment
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: sigsci-service
    spec:
      containers:
      - name: sigsci-service
        image: signalsciences/sigsci-agent
        env:
        - name: SIGSCI_SECRETACCESSKEY
          value: "setme"
        - name: SIGSCI_ACCESSKEYID
          value: "setme"
        - name: SIGSCI_REVPROXY_LISTENER
          value: "proxy:{listener=http://0.0.0.0:80,upstreams=http://servicename:80}"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sigsci-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: sigsci-service