FROM alpine:latest

RUN apk update && apk add --no-cache openssl-dev haproxy apache2 ca-certificates curl wget make build-base readline-dev 

RUN curl -R -O http://www.lua.org/ftp/lua-5.3.5.tar.gz && tar zxf lua-5.3.5.tar.gz && cd lua-5.3.5 && make linux test

RUN wget https://dl.signalsciences.net/sigsci-module-haproxy/1.1.4/alpine/3.6/sigsci-module-haproxy_1.1.4-3.6_all.apk && apk add --allow-untrusted sigsci-module-haproxy_1.1.4-3.6_all.apk
RUN wget https://dl.signalsciences.net/sigsci-agent/sigsci-agent_latest.tar.gz && tar -xvf sigsci-agent_latest.tar.gz
RUN mkdir /app && mkdir /etc/sigsci && mkdir /run/haproxy && mkdir /run/apache2
COPY start.sh /app/start.sh
RUN chmod +x /app/start.sh
COPY app/httpd.conf /etc/apache2/httpd.conf
COPY app/haproxy.cfg /etc/haproxy/haproxy.cfg
COPY app/index.html /var/www/localhost/htdocs/index.html

ENTRYPOINT ["/app/start.sh"]

