---
# Ansible Playbook for SigSci Install
- hosts: [web]

  tasks:
  - name: "Add SigSci source list and gpg key on Ubuntu"
    script: sigsci_install_ubuntu.sh
    when: ansible_distribution == "Ubuntu"

  - name: "Update apt"
    shell: apt-get update --allow-unauthenticated
    
  - name: "Install Apache2"
    apt: name=apache2 state=latest
    when: ansible_distribution == "Ubuntu"
  
  - name: "Install SigSci agent"
    shell: apt-get install -y --allow-unauthenticated sigsci-agent

  - name: "Create /etc/sigsci directory"
    file: path=/etc/sigsci state=directory
    when: ansible_distribution == "Ubuntu"

  - copy: src=agent.conf dest=/etc/sigsci/agent.conf
    when: ansible_distribution == "Ubuntu"
  
  - name: "Start sigsci agent" 
    service:
      name: sigsci-agent
      state: restarted
 
  - name: "apt-get install sigsci-module-apache"
    shell: apt-get install -y --allow-unauthenticated sigsci-module-apache
 
  - name: "Enable SigSci Apache2 module"
    apache2_module: name=signalsciences state=present
    when: ansible_distribution == "Ubuntu"
 
  - name: "Restart Apache2"
    service:
      name: apache2
      state: restarted